apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  FRONTEND_URL: "http://frontend:3000"
  SERVICE1_URL: "http://service1:5000"
  SERVICE2_URL: "http://service2:5001"
  DATABASE_URL: "postgres://root:root_password@postgres:5432/main_db"
